### ISSUE TITLE
Include recoll in the release

### ISSUE THREAD

**Issue by Skodddy** [idealist1508/Recoll-Full-Text-Search-For-Calibre#1]
Can you include the windows binary version of recoll in your release?

**Comment by idealist1508** [comment]
You can get it here: https://www.lesbonscomptes.com/recoll/pages/recoll-windows.html

**Comment by Skodddy** [comment]
It's under GNU, can you share it here?

**Comment by idealist1508** [comment]
You can build it from source http://www.lesbonscomptes.com/recoll/download.html#source,  if you don't have 5 Euro.
