### ISSUE TITLE
Config Directory and Calibre Library Directory confusion

### ISSUE THREAD

**Issue by goodev2021** [idealist1508/Recoll-Full-Text-Search-For-Calibre#3]
Can you please attach a screenshot of Customize Recoll Full Text Search screen as well as the value to be given in Config Directory and Calibre Library Directory ...This is quite confusing with the latest Calibre version

Can you please help with the steps as well as screenshots....

Also, if possible update the plugin to compatible with the latest version of calibre

**Comment by idealist1508** [comment]
You've seen #2. Is it that what you mean with "Customize Recoll Full Text Search screen"
